var request = require("request");

var options = {
    method: 'POST',
    // url: 'http://jsonplaceholder.typicode.com/posts', // '***REMOVED***'
    url: '***REMOVED***', // 'http://jsonplaceholder.typicode.com/posts',
    headers: {
        'cache-control': 'no-cache',
        'content-type': 'application/json'
    }
};


var derp = ('{  "type": 2,  "nsp": "/",  "data": [    "score",    {      "mapScores": {},      "listId": 2312129,      "wins": {},      "liveLog": {        "": true,        "IrregularTeamKillsRequirement": true,        "PlayersRequirement": true,        "NoSuspectEventsInFirstRoundRequirement": true,        "NotKnifeRoundRequirement": false,        "BombInPlayRequirement": true,        "FiveKillsWhenEnemyElliminatedRequirement less than 5 five kills in round(s) []": true,        "MatchStartRequirement": true,        "MapNameRequirement": true,        "NoDrawRoundsRequirement": true,        "FirstRoundOverRequirement": true,        "RoundOneMaxEquipmentValueRequirement": true      },      "forcedLive": false,      "forcedDead": false    }  ]}');

options.body = derp;

// should see id = 101, the fake id generated by jsonplaceholder
request(options, function(error, response, body) {
    if (error) throw new Error(error);
    console.log(body);
});
